[package]
name = "hardware-wallet-chain-bitcoin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
hardware-wallet-chain-api = { path = "../chain-api" }

[dev-dependencies]
hardware-wallet-core = { path = "../wallet-core" }
hardware-wallet-crypto-runtime = { path = "../crypto-runtime" }

[lints]
workspace = true
